package sdl

func init() {
    registerLoaderFunc(func() []externFunc {
        return []externFunc {
            { &GetNumAudioDrivers, "SDL_GetNumAudioDrivers" },
            { &GetAudioDriver, "SDL_GetAudioDriver" },
            { &GetCurrentAudioDriver, "SDL_GetCurrentAudioDriver" },
            { &GetAudioPlaybackDevices, "SDL_GetAudioPlaybackDevices" },
            { &GetAudioRecordingDevices, "SDL_GetAudioRecordingDevices" },
            { &GetAudioDeviceName, "SDL_GetAudioDeviceName" },
            { &GetAudioDeviceFormat, "SDL_GetAudioDeviceFormat" },
            { &GetAudioDeviceChannelMap, "SDL_GetAudioDeviceChannelMap" },
            { &OpenAudioDevice, "SDL_OpenAudioDevice" },
            { &IsAudioDevicePhysical, "SDL_IsAudioDevicePhysical" },
            { &IsAudioDevicePlayback, "SDL_IsAudioDevicePlayback" },
            { &PauseAudioDevice, "SDL_PauseAudioDevice" },
            { &ResumeAudioDevice, "SDL_ResumeAudioDevice" },
            { &AudioDevicePaused, "SDL_AudioDevicePaused" },
            { &GetAudioDeviceGain, "SDL_GetAudioDeviceGain" },
            { &SetAudioDeviceGain, "SDL_SetAudioDeviceGain" },
            { &CloseAudioDevice, "SDL_CloseAudioDevice" },
            { &BindAudioStreams, "SDL_BindAudioStreams" },
            { &BindAudioStream, "SDL_BindAudioStream" },
            { &UnbindAudioStreams, "SDL_UnbindAudioStreams" },
            { &UnbindAudioStream, "SDL_UnbindAudioStream" },
            { &GetAudioStreamDevice, "SDL_GetAudioStreamDevice" },
            { &CreateAudioStream, "SDL_CreateAudioStream" },
            { &GetAudioStreamProperties, "SDL_GetAudioStreamProperties" },
            { &GetAudioStreamFormat, "SDL_GetAudioStreamFormat" },
            { &SetAudioStreamFormat, "SDL_SetAudioStreamFormat" },
            { &GetAudioStreamFrequencyRatio, "SDL_GetAudioStreamFrequencyRatio" },
            { &SetAudioStreamFrequencyRatio, "SDL_SetAudioStreamFrequencyRatio" },
            { &GetAudioStreamGain, "SDL_GetAudioStreamGain" },
            { &SetAudioStreamGain, "SDL_SetAudioStreamGain" },
            { &GetAudioStreamInputChannelMap, "SDL_GetAudioStreamInputChannelMap" },
            { &GetAudioStreamOutputChannelMap, "SDL_GetAudioStreamOutputChannelMap" },
            { &SetAudioStreamInputChannelMap, "SDL_SetAudioStreamInputChannelMap" },
            { &SetAudioStreamOutputChannelMap, "SDL_SetAudioStreamOutputChannelMap" },
            { &PutAudioStreamData, "SDL_PutAudioStreamData" },
            { &PutAudioStreamPlanarData, "SDL_PutAudioStreamPlanarData" },
            { &GetAudioStreamData, "SDL_GetAudioStreamData" },
            { &GetAudioStreamAvailable, "SDL_GetAudioStreamAvailable" },
            { &GetAudioStreamQueued, "SDL_GetAudioStreamQueued" },
            { &FlushAudioStream, "SDL_FlushAudioStream" },
            { &ClearAudioStream, "SDL_ClearAudioStream" },
            { &PauseAudioStreamDevice, "SDL_PauseAudioStreamDevice" },
            { &ResumeAudioStreamDevice, "SDL_ResumeAudioStreamDevice" },
            { &AudioStreamDevicePaused, "SDL_AudioStreamDevicePaused" },
            { &LockAudioStream, "SDL_LockAudioStream" },
            { &UnlockAudioStream, "SDL_UnlockAudioStream" },
            { &SetAudioStreamGetCallback, "SDL_SetAudioStreamGetCallback" },
            { &SetAudioStreamPutCallback, "SDL_SetAudioStreamPutCallback" },
            { &DestroyAudioStream, "SDL_DestroyAudioStream" },
            { &OpenAudioDeviceStream, "SDL_OpenAudioDeviceStream" },
            { &SetAudioIterationCallbacks, "SDL_SetAudioIterationCallbacks" },
            { &SetAudioPostmixCallback, "SDL_SetAudioPostmixCallback" },
            { &LoadWAV_IO, "SDL_LoadWAV_IO" },
            { &LoadWAV, "SDL_LoadWAV" },
            { &MixAudio, "SDL_MixAudio" },
            { &ConvertAudioSamples, "SDL_ConvertAudioSamples" },
            { &GetAudioFormatName, "SDL_GetAudioFormatName" },
            { &GetSilenceValueForFormat, "SDL_GetSilenceValueForFormat" },
        }
    })
}
