package sdl

func init() {
    registerLoaderFunc(func() []externFunc {
        return []externFunc {
            { &AddGamepadMapping, "SDL_AddGamepadMapping" },
            { &AddGamepadMappingsFromIO, "SDL_AddGamepadMappingsFromIO" },
            { &AddGamepadMappingsFromFile, "SDL_AddGamepadMappingsFromFile" },
            { &ReloadGamepadMappings, "SDL_ReloadGamepadMappings" },
            { &GetGamepadMappings, "SDL_GetGamepadMappings" },
            { &GetGamepadMappingForGUID, "SDL_GetGamepadMappingForGUID" },
            { &GetGamepadMapping, "SDL_GetGamepadMapping" },
            { &SetGamepadMapping, "SDL_SetGamepadMapping" },
            { &HasGamepad, "SDL_HasGamepad" },
            { &GetGamepads, "SDL_GetGamepads" },
            { &IsGamepad, "SDL_IsGamepad" },
            { &GetGamepadNameForID, "SDL_GetGamepadNameForID" },
            { &GetGamepadPathForID, "SDL_GetGamepadPathForID" },
            { &GetGamepadPlayerIndexForID, "SDL_GetGamepadPlayerIndexForID" },
            { &GetGamepadGUIDForID, "SDL_GetGamepadGUIDForID" },
            { &GetGamepadVendorForID, "SDL_GetGamepadVendorForID" },
            { &GetGamepadProductForID, "SDL_GetGamepadProductForID" },
            { &GetGamepadProductVersionForID, "SDL_GetGamepadProductVersionForID" },
            { &GetGamepadTypeForID, "SDL_GetGamepadTypeForID" },
            { &GetRealGamepadTypeForID, "SDL_GetRealGamepadTypeForID" },
            { &GetGamepadMappingForID, "SDL_GetGamepadMappingForID" },
            { &OpenGamepad, "SDL_OpenGamepad" },
            { &GetGamepadFromID, "SDL_GetGamepadFromID" },
            { &GetGamepadFromPlayerIndex, "SDL_GetGamepadFromPlayerIndex" },
            { &GetGamepadProperties, "SDL_GetGamepadProperties" },
            { &GetGamepadID, "SDL_GetGamepadID" },
            { &GetGamepadName, "SDL_GetGamepadName" },
            { &GetGamepadPath, "SDL_GetGamepadPath" },
            { &GetGamepadType, "SDL_GetGamepadType" },
            { &GetRealGamepadType, "SDL_GetRealGamepadType" },
            { &GetGamepadPlayerIndex, "SDL_GetGamepadPlayerIndex" },
            { &SetGamepadPlayerIndex, "SDL_SetGamepadPlayerIndex" },
            { &GetGamepadVendor, "SDL_GetGamepadVendor" },
            { &GetGamepadProduct, "SDL_GetGamepadProduct" },
            { &GetGamepadProductVersion, "SDL_GetGamepadProductVersion" },
            { &GetGamepadFirmwareVersion, "SDL_GetGamepadFirmwareVersion" },
            { &GetGamepadSerial, "SDL_GetGamepadSerial" },
            { &GetGamepadSteamHandle, "SDL_GetGamepadSteamHandle" },
            { &GetGamepadConnectionState, "SDL_GetGamepadConnectionState" },
            { &GetGamepadPowerInfo, "SDL_GetGamepadPowerInfo" },
            { &GamepadConnected, "SDL_GamepadConnected" },
            { &GetGamepadJoystick, "SDL_GetGamepadJoystick" },
            { &SetGamepadEventsEnabled, "SDL_SetGamepadEventsEnabled" },
            { &GamepadEventsEnabled, "SDL_GamepadEventsEnabled" },
            { &GetGamepadBindings, "SDL_GetGamepadBindings" },
            { &UpdateGamepads, "SDL_UpdateGamepads" },
            { &GetGamepadTypeFromString, "SDL_GetGamepadTypeFromString" },
            { &GetGamepadStringForType, "SDL_GetGamepadStringForType" },
            { &GetGamepadAxisFromString, "SDL_GetGamepadAxisFromString" },
            { &GetGamepadStringForAxis, "SDL_GetGamepadStringForAxis" },
            { &GamepadHasAxis, "SDL_GamepadHasAxis" },
            { &GetGamepadAxis, "SDL_GetGamepadAxis" },
            { &GetGamepadButtonFromString, "SDL_GetGamepadButtonFromString" },
            { &GetGamepadStringForButton, "SDL_GetGamepadStringForButton" },
            { &GamepadHasButton, "SDL_GamepadHasButton" },
            { &GetGamepadButton, "SDL_GetGamepadButton" },
            { &GetGamepadButtonLabelForType, "SDL_GetGamepadButtonLabelForType" },
            { &GetGamepadButtonLabel, "SDL_GetGamepadButtonLabel" },
            { &GetNumGamepadTouchpads, "SDL_GetNumGamepadTouchpads" },
            { &GetNumGamepadTouchpadFingers, "SDL_GetNumGamepadTouchpadFingers" },
            { &GetGamepadTouchpadFinger, "SDL_GetGamepadTouchpadFinger" },
            { &GamepadHasSensor, "SDL_GamepadHasSensor" },
            { &SetGamepadSensorEnabled, "SDL_SetGamepadSensorEnabled" },
            { &GamepadSensorEnabled, "SDL_GamepadSensorEnabled" },
            { &GetGamepadSensorDataRate, "SDL_GetGamepadSensorDataRate" },
            { &GetGamepadSensorData, "SDL_GetGamepadSensorData" },
            { &RumbleGamepad, "SDL_RumbleGamepad" },
            { &RumbleGamepadTriggers, "SDL_RumbleGamepadTriggers" },
            { &SetGamepadLED, "SDL_SetGamepadLED" },
            { &SendGamepadEffect, "SDL_SendGamepadEffect" },
            { &CloseGamepad, "SDL_CloseGamepad" },
            { &GetGamepadAppleSFSymbolsNameForButton, "SDL_GetGamepadAppleSFSymbolsNameForButton" },
            { &GetGamepadAppleSFSymbolsNameForAxis, "SDL_GetGamepadAppleSFSymbolsNameForAxis" },
        }
    })
}
