package sdl

func init() {
    registerLoaderFunc(func() []externFunc {
        return []externFunc {
            { &IOFromFile, "SDL_IOFromFile" },
            { &IOFromMem, "SDL_IOFromMem" },
            { &IOFromConstMem, "SDL_IOFromConstMem" },
            { &IOFromDynamicMem, "SDL_IOFromDynamicMem" },
            { &OpenIO, "SDL_OpenIO" },
            { &CloseIO, "SDL_CloseIO" },
            { &GetIOProperties, "SDL_GetIOProperties" },
            { &GetIOStatus, "SDL_GetIOStatus" },
            { &GetIOSize, "SDL_GetIOSize" },
            { &SeekIO, "SDL_SeekIO" },
            { &TellIO, "SDL_TellIO" },
            { &ReadIO, "SDL_ReadIO" },
            { &WriteIO, "SDL_WriteIO" },
            { &FlushIO, "SDL_FlushIO" },
            { &LoadFile_IO, "SDL_LoadFile_IO" },
            { &LoadFile, "SDL_LoadFile" },
            { &SaveFile_IO, "SDL_SaveFile_IO" },
            { &SaveFile, "SDL_SaveFile" },
            { &ReadU8, "SDL_ReadU8" },
            { &ReadS8, "SDL_ReadS8" },
            { &ReadU16LE, "SDL_ReadU16LE" },
            { &ReadS16LE, "SDL_ReadS16LE" },
            { &ReadU16BE, "SDL_ReadU16BE" },
            { &ReadS16BE, "SDL_ReadS16BE" },
            { &ReadU32LE, "SDL_ReadU32LE" },
            { &ReadS32LE, "SDL_ReadS32LE" },
            { &ReadU32BE, "SDL_ReadU32BE" },
            { &ReadS32BE, "SDL_ReadS32BE" },
            { &ReadU64LE, "SDL_ReadU64LE" },
            { &ReadS64LE, "SDL_ReadS64LE" },
            { &ReadU64BE, "SDL_ReadU64BE" },
            { &ReadS64BE, "SDL_ReadS64BE" },
            { &WriteU8, "SDL_WriteU8" },
            { &WriteS8, "SDL_WriteS8" },
            { &WriteU16LE, "SDL_WriteU16LE" },
            { &WriteS16LE, "SDL_WriteS16LE" },
            { &WriteU16BE, "SDL_WriteU16BE" },
            { &WriteS16BE, "SDL_WriteS16BE" },
            { &WriteU32LE, "SDL_WriteU32LE" },
            { &WriteS32LE, "SDL_WriteS32LE" },
            { &WriteU32BE, "SDL_WriteU32BE" },
            { &WriteS32BE, "SDL_WriteS32BE" },
            { &WriteU64LE, "SDL_WriteU64LE" },
            { &WriteS64LE, "SDL_WriteS64LE" },
            { &WriteU64BE, "SDL_WriteU64BE" },
            { &WriteS64BE, "SDL_WriteS64BE" },
        }
    })
}
