package sdl

import "github.com/ebitengine/purego"

func init() {
    registerLoaderFunc(func(lib uintptr) {
        purego.RegisterLibFunc(&IOFromFile, lib, "SDL_IOFromFile")
        purego.RegisterLibFunc(&IOFromMem, lib, "SDL_IOFromMem")
        purego.RegisterLibFunc(&IOFromConstMem, lib, "SDL_IOFromConstMem")
        purego.RegisterLibFunc(&IOFromDynamicMem, lib, "SDL_IOFromDynamicMem")
        purego.RegisterLibFunc(&OpenIO, lib, "SDL_OpenIO")
        purego.RegisterLibFunc(&CloseIO, lib, "SDL_CloseIO")
        purego.RegisterLibFunc(&GetIOProperties, lib, "SDL_GetIOProperties")
        purego.RegisterLibFunc(&GetIOStatus, lib, "SDL_GetIOStatus")
        purego.RegisterLibFunc(&GetIOSize, lib, "SDL_GetIOSize")
        purego.RegisterLibFunc(&SeekIO, lib, "SDL_SeekIO")
        purego.RegisterLibFunc(&TellIO, lib, "SDL_TellIO")
        purego.RegisterLibFunc(&ReadIO, lib, "SDL_ReadIO")
        purego.RegisterLibFunc(&WriteIO, lib, "SDL_WriteIO")
        purego.RegisterLibFunc(&FlushIO, lib, "SDL_FlushIO")
        purego.RegisterLibFunc(&LoadFile_IO, lib, "SDL_LoadFile_IO")
        purego.RegisterLibFunc(&LoadFile, lib, "SDL_LoadFile")
        purego.RegisterLibFunc(&SaveFile_IO, lib, "SDL_SaveFile_IO")
        purego.RegisterLibFunc(&SaveFile, lib, "SDL_SaveFile")
        purego.RegisterLibFunc(&ReadU8, lib, "SDL_ReadU8")
        purego.RegisterLibFunc(&ReadS8, lib, "SDL_ReadS8")
        purego.RegisterLibFunc(&ReadU16LE, lib, "SDL_ReadU16LE")
        purego.RegisterLibFunc(&ReadS16LE, lib, "SDL_ReadS16LE")
        purego.RegisterLibFunc(&ReadU16BE, lib, "SDL_ReadU16BE")
        purego.RegisterLibFunc(&ReadS16BE, lib, "SDL_ReadS16BE")
        purego.RegisterLibFunc(&ReadU32LE, lib, "SDL_ReadU32LE")
        purego.RegisterLibFunc(&ReadS32LE, lib, "SDL_ReadS32LE")
        purego.RegisterLibFunc(&ReadU32BE, lib, "SDL_ReadU32BE")
        purego.RegisterLibFunc(&ReadS32BE, lib, "SDL_ReadS32BE")
        purego.RegisterLibFunc(&ReadU64LE, lib, "SDL_ReadU64LE")
        purego.RegisterLibFunc(&ReadS64LE, lib, "SDL_ReadS64LE")
        purego.RegisterLibFunc(&ReadU64BE, lib, "SDL_ReadU64BE")
        purego.RegisterLibFunc(&ReadS64BE, lib, "SDL_ReadS64BE")
        purego.RegisterLibFunc(&WriteU8, lib, "SDL_WriteU8")
        purego.RegisterLibFunc(&WriteS8, lib, "SDL_WriteS8")
        purego.RegisterLibFunc(&WriteU16LE, lib, "SDL_WriteU16LE")
        purego.RegisterLibFunc(&WriteS16LE, lib, "SDL_WriteS16LE")
        purego.RegisterLibFunc(&WriteU16BE, lib, "SDL_WriteU16BE")
        purego.RegisterLibFunc(&WriteS16BE, lib, "SDL_WriteS16BE")
        purego.RegisterLibFunc(&WriteU32LE, lib, "SDL_WriteU32LE")
        purego.RegisterLibFunc(&WriteS32LE, lib, "SDL_WriteS32LE")
        purego.RegisterLibFunc(&WriteU32BE, lib, "SDL_WriteU32BE")
        purego.RegisterLibFunc(&WriteS32BE, lib, "SDL_WriteS32BE")
        purego.RegisterLibFunc(&WriteU64LE, lib, "SDL_WriteU64LE")
        purego.RegisterLibFunc(&WriteS64LE, lib, "SDL_WriteS64LE")
        purego.RegisterLibFunc(&WriteU64BE, lib, "SDL_WriteU64BE")
        purego.RegisterLibFunc(&WriteS64BE, lib, "SDL_WriteS64BE")
        
    })
}
