package sdl

func init() {
    registerLoaderFunc(func() []externFunc {
        return []externFunc {
            { &LockJoysticks, "SDL_LockJoysticks" },
            { &UnlockJoysticks, "SDL_UnlockJoysticks" },
            { &HasJoystick, "SDL_HasJoystick" },
            { &GetJoysticks, "SDL_GetJoysticks" },
            { &GetJoystickNameForID, "SDL_GetJoystickNameForID" },
            { &GetJoystickPathForID, "SDL_GetJoystickPathForID" },
            { &GetJoystickPlayerIndexForID, "SDL_GetJoystickPlayerIndexForID" },
            { &GetJoystickGUIDForID, "SDL_GetJoystickGUIDForID" },
            { &GetJoystickVendorForID, "SDL_GetJoystickVendorForID" },
            { &GetJoystickProductForID, "SDL_GetJoystickProductForID" },
            { &GetJoystickProductVersionForID, "SDL_GetJoystickProductVersionForID" },
            { &GetJoystickTypeForID, "SDL_GetJoystickTypeForID" },
            { &OpenJoystick, "SDL_OpenJoystick" },
            { &GetJoystickFromID, "SDL_GetJoystickFromID" },
            { &GetJoystickFromPlayerIndex, "SDL_GetJoystickFromPlayerIndex" },
            { &AttachVirtualJoystick, "SDL_AttachVirtualJoystick" },
            { &DetachVirtualJoystick, "SDL_DetachVirtualJoystick" },
            { &IsJoystickVirtual, "SDL_IsJoystickVirtual" },
            { &SetJoystickVirtualAxis, "SDL_SetJoystickVirtualAxis" },
            { &SetJoystickVirtualBall, "SDL_SetJoystickVirtualBall" },
            { &SetJoystickVirtualButton, "SDL_SetJoystickVirtualButton" },
            { &SetJoystickVirtualHat, "SDL_SetJoystickVirtualHat" },
            { &SetJoystickVirtualTouchpad, "SDL_SetJoystickVirtualTouchpad" },
            { &SendJoystickVirtualSensorData, "SDL_SendJoystickVirtualSensorData" },
            { &GetJoystickProperties, "SDL_GetJoystickProperties" },
            { &GetJoystickName, "SDL_GetJoystickName" },
            { &GetJoystickPath, "SDL_GetJoystickPath" },
            { &GetJoystickPlayerIndex, "SDL_GetJoystickPlayerIndex" },
            { &SetJoystickPlayerIndex, "SDL_SetJoystickPlayerIndex" },
            { &GetJoystickGUID, "SDL_GetJoystickGUID" },
            { &GetJoystickVendor, "SDL_GetJoystickVendor" },
            { &GetJoystickProduct, "SDL_GetJoystickProduct" },
            { &GetJoystickProductVersion, "SDL_GetJoystickProductVersion" },
            { &GetJoystickFirmwareVersion, "SDL_GetJoystickFirmwareVersion" },
            { &GetJoystickSerial, "SDL_GetJoystickSerial" },
            { &GetJoystickType, "SDL_GetJoystickType" },
            { &GetJoystickGUIDInfo, "SDL_GetJoystickGUIDInfo" },
            { &JoystickConnected, "SDL_JoystickConnected" },
            { &GetJoystickID, "SDL_GetJoystickID" },
            { &GetNumJoystickAxes, "SDL_GetNumJoystickAxes" },
            { &GetNumJoystickBalls, "SDL_GetNumJoystickBalls" },
            { &GetNumJoystickHats, "SDL_GetNumJoystickHats" },
            { &GetNumJoystickButtons, "SDL_GetNumJoystickButtons" },
            { &SetJoystickEventsEnabled, "SDL_SetJoystickEventsEnabled" },
            { &JoystickEventsEnabled, "SDL_JoystickEventsEnabled" },
            { &UpdateJoysticks, "SDL_UpdateJoysticks" },
            { &GetJoystickAxis, "SDL_GetJoystickAxis" },
            { &GetJoystickAxisInitialState, "SDL_GetJoystickAxisInitialState" },
            { &GetJoystickBall, "SDL_GetJoystickBall" },
            { &GetJoystickHat, "SDL_GetJoystickHat" },
            { &GetJoystickButton, "SDL_GetJoystickButton" },
            { &RumbleJoystick, "SDL_RumbleJoystick" },
            { &RumbleJoystickTriggers, "SDL_RumbleJoystickTriggers" },
            { &SetJoystickLED, "SDL_SetJoystickLED" },
            { &SendJoystickEffect, "SDL_SendJoystickEffect" },
            { &CloseJoystick, "SDL_CloseJoystick" },
            { &GetJoystickConnectionState, "SDL_GetJoystickConnectionState" },
            { &GetJoystickPowerInfo, "SDL_GetJoystickPowerInfo" },
        }
    })
}
