/*
  Simple DirectMedia Layer
  Copyright (C) 1997-2025 Sam Lantinga <slouken@libsdl.org>

  This software is provided 'as-is', without any express or implied
  warranty.  In no event will the authors be held liable for any damages
  arising from the use of this software.

  Permission is granted to anyone to use this software for any purpose,
  including commercial applications, and to alter it and redistribute it
  freely, subject to the following restrictions:

  1. The origin of this software must not be misrepresented; you must not
     claim that you wrote the original software. If you use this software
     in a product, an acknowledgment in the product documentation would be
     appreciated but is not required.
  2. Altered source versions must be plainly marked as such, and must not be
     misrepresented as being the original software.
  3. This notice may not be removed or altered from any source distribution.
*/

/*
  Language bindings and additional adaptations by AleD, 2025
  This file contains modified code and/or translated interfaces.
  Original SDL3 source: https://github.com/libsdl-org/SDL
*/

/**
 * # CategoryKeycode
 *
 * Defines constants which identify keyboard keys and modifiers.
 *
 * Please refer to the Best Keyboard Practices document for details on what
 * this information means and how best to use it.
 *
 * https://wiki.libsdl.org/SDL3/BestKeyboardPractices
 */
package sdl

/**
 * The SDL virtual key representation.
 *
 * Values of this type are used to represent keyboard keys using the current
 * layout of the keyboard. These values include Unicode values representing
 * the unmodified character that would be generated by pressing the key, or an
 * `SDLK_*` constant for those keys that do not generate characters.
 *
 * A special exception is the number keys at the top of the keyboard which map
 * to SDLK_0...SDLK_9 on AZERTY layouts.
 *
 * Keys with the `SDLK_EXTENDED_MASK` bit set do not map to a scancode or
 * unicode code point.
 *
 * \since This datatype is available since SDL 3.2.0.
 */
type Keycode uint32

const (
	EXTENDED_MASK = (1 << 29)
	SCANCODE_MASK = (1 << 30)
)

func SCANCODE_TO_KEYCODE(X int) Keycode {
	return Keycode(X | SCANCODE_MASK)
}

const (
	KC_Unknown            Keycode = 0x00000000 /**< 0 */
	KC_Return             Keycode = 0x0000000d /**< '\r' */
	KC_Escape             Keycode = 0x0000001b /**< '\x1B' */
	KC_Backspace          Keycode = 0x00000008 /**< '\b' */
	KC_Tab                Keycode = 0x00000009 /**< '\t' */
	KC_Space              Keycode = 0x00000020 /**< ' ' */
	KC_Exclaim            Keycode = 0x00000021 /**< '!' */
	KC_DblApostrophe      Keycode = 0x00000022 /**< '"' */
	KC_Hash               Keycode = 0x00000023 /**< '#' */
	KC_Dollar             Keycode = 0x00000024 /**< '$' */
	KC_Percent            Keycode = 0x00000025 /**< '%' */
	KC_Ampersand          Keycode = 0x00000026 /**< '&' */
	KC_Apostrophe         Keycode = 0x00000027 /**< '\'' */
	KC_LeftParen          Keycode = 0x00000028 /**< '(' */
	KC_RightParen         Keycode = 0x00000029 /**< ')' */
	KC_Asterisk           Keycode = 0x0000002a /**< '*' */
	KC_Plus               Keycode = 0x0000002b /**< '+' */
	KC_Comma              Keycode = 0x0000002c /**< ',' */
	KC_Minus              Keycode = 0x0000002d /**< '-' */
	KC_Period             Keycode = 0x0000002e /**< '.' */
	KC_Slash              Keycode = 0x0000002f /**< '/' */
	KC_0                  Keycode = 0x00000030 /**< '0' */
	KC_1                  Keycode = 0x00000031 /**< '1' */
	KC_2                  Keycode = 0x00000032 /**< '2' */
	KC_3                  Keycode = 0x00000033 /**< '3' */
	KC_4                  Keycode = 0x00000034 /**< '4' */
	KC_5                  Keycode = 0x00000035 /**< '5' */
	KC_6                  Keycode = 0x00000036 /**< '6' */
	KC_7                  Keycode = 0x00000037 /**< '7' */
	KC_8                  Keycode = 0x00000038 /**< '8' */
	KC_9                  Keycode = 0x00000039 /**< '9' */
	KC_Colon              Keycode = 0x0000003a /**< ':' */
	KC_Semicolon          Keycode = 0x0000003b /**< ';' */
	KC_Less               Keycode = 0x0000003c /**< '<' */
	KC_Equals             Keycode = 0x0000003d /**< '=' */
	KC_Greater            Keycode = 0x0000003e /**< '>' */
	KC_Question           Keycode = 0x0000003f /**< '?' */
	KC_At                 Keycode = 0x00000040 /**< '@' */
	KC_LeftBracket        Keycode = 0x0000005b /**< '[' */
	KC_Backslash          Keycode = 0x0000005c /**< '\\' */
	KC_RightBracket       Keycode = 0x0000005d /**< ']' */
	KC_Caret              Keycode = 0x0000005e /**< '^' */
	KC_Underscore         Keycode = 0x0000005f /**< '_' */
	KC_Grave              Keycode = 0x00000060 /**< '`' */
	KC_A                  Keycode = 0x00000061 /**< 'a' */
	KC_B                  Keycode = 0x00000062 /**< 'b' */
	KC_C                  Keycode = 0x00000063 /**< 'c' */
	KC_D                  Keycode = 0x00000064 /**< 'd' */
	KC_E                  Keycode = 0x00000065 /**< 'e' */
	KC_F                  Keycode = 0x00000066 /**< 'f' */
	KC_G                  Keycode = 0x00000067 /**< 'g' */
	KC_H                  Keycode = 0x00000068 /**< 'h' */
	KC_I                  Keycode = 0x00000069 /**< 'i' */
	KC_J                  Keycode = 0x0000006a /**< 'j' */
	KC_K                  Keycode = 0x0000006b /**< 'k' */
	KC_L                  Keycode = 0x0000006c /**< 'l' */
	KC_M                  Keycode = 0x0000006d /**< 'm' */
	KC_N                  Keycode = 0x0000006e /**< 'n' */
	KC_O                  Keycode = 0x0000006f /**< 'o' */
	KC_P                  Keycode = 0x00000070 /**< 'p' */
	KC_Q                  Keycode = 0x00000071 /**< 'q' */
	KC_R                  Keycode = 0x00000072 /**< 'r' */
	KC_S                  Keycode = 0x00000073 /**< 's' */
	KC_T                  Keycode = 0x00000074 /**< 't' */
	KC_U                  Keycode = 0x00000075 /**< 'u' */
	KC_V                  Keycode = 0x00000076 /**< 'v' */
	KC_W                  Keycode = 0x00000077 /**< 'w' */
	KC_X                  Keycode = 0x00000078 /**< 'x' */
	KC_Y                  Keycode = 0x00000079 /**< 'y' */
	KC_Z                  Keycode = 0x0000007a /**< 'z' */
	KC_LeftBrace          Keycode = 0x0000007b /**< '{' */
	KC_Pipe               Keycode = 0x0000007c /**< '|' */
	KC_RightBrace         Keycode = 0x0000007d /**< '}' */
	KC_Tilde              Keycode = 0x0000007e /**< '~' */
	KC_Delete             Keycode = 0x0000007f /**< '\x7F' */
	KC_PlusMinus          Keycode = 0x000000b1 /**< '\xB1' */
	KC_CapsLock           Keycode = 0x40000039 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CAPSLOCK) */
	KC_F1                 Keycode = 0x4000003a /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F1) */
	KC_F2                 Keycode = 0x4000003b /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F2) */
	KC_F3                 Keycode = 0x4000003c /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F3) */
	KC_F4                 Keycode = 0x4000003d /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F4) */
	KC_F5                 Keycode = 0x4000003e /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F5) */
	KC_F6                 Keycode = 0x4000003f /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F6) */
	KC_F7                 Keycode = 0x40000040 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F7) */
	KC_F8                 Keycode = 0x40000041 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F8) */
	KC_F9                 Keycode = 0x40000042 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F9) */
	KC_F10                Keycode = 0x40000043 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F10) */
	KC_F11                Keycode = 0x40000044 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F11) */
	KC_F12                Keycode = 0x40000045 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F12) */
	KC_PrintScreen        Keycode = 0x40000046 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PRINTSCREEN) */
	KC_ScrollLock         Keycode = 0x40000047 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SCROLLLOCK) */
	KC_Pause              Keycode = 0x40000048 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PAUSE) */
	KC_Insert             Keycode = 0x40000049 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_INSERT) */
	KC_Home               Keycode = 0x4000004a /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_HOME) */
	KC_PageUp             Keycode = 0x4000004b /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PAGEUP) */
	KC_End                Keycode = 0x4000004d /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_END) */
	KC_PageDown           Keycode = 0x4000004e /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PAGEDOWN) */
	KC_Right              Keycode = 0x4000004f /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RIGHT) */
	KC_Left               Keycode = 0x40000050 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LEFT) */
	KC_Down               Keycode = 0x40000051 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_DOWN) */
	KC_Up                 Keycode = 0x40000052 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_UP) */
	KC_NumLockClear       Keycode = 0x40000053 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_NUMLOCKCLEAR) */
	KC_KP_Divide          Keycode = 0x40000054 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DIVIDE) */
	KC_KP_Multiply        Keycode = 0x40000055 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MULTIPLY) */
	KC_KP_Minus           Keycode = 0x40000056 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MINUS) */
	KC_KP_Plus            Keycode = 0x40000057 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PLUS) */
	KC_KP_Enter           Keycode = 0x40000058 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_ENTER) */
	KC_KP_1               Keycode = 0x40000059 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_1) */
	KC_KP_2               Keycode = 0x4000005a /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_2) */
	KC_KP_3               Keycode = 0x4000005b /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_3) */
	KC_KP_4               Keycode = 0x4000005c /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_4) */
	KC_KP_5               Keycode = 0x4000005d /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_5) */
	KC_KP_6               Keycode = 0x4000005e /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_6) */
	KC_KP_7               Keycode = 0x4000005f /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_7) */
	KC_KP_8               Keycode = 0x40000060 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_8) */
	KC_KP_9               Keycode = 0x40000061 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_9) */
	KC_KP_0               Keycode = 0x40000062 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_0) */
	KC_KP_Period          Keycode = 0x40000063 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PERIOD) */
	KC_Application        Keycode = 0x40000065 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_APPLICATION) */
	KC_Power              Keycode = 0x40000066 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_POWER) */
	KC_KP_Equals          Keycode = 0x40000067 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_EQUALS) */
	KC_F13                Keycode = 0x40000068 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F13) */
	KC_F14                Keycode = 0x40000069 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F14) */
	KC_F15                Keycode = 0x4000006a /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F15) */
	KC_F16                Keycode = 0x4000006b /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F16) */
	KC_F17                Keycode = 0x4000006c /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F17) */
	KC_F18                Keycode = 0x4000006d /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F18) */
	KC_F19                Keycode = 0x4000006e /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F19) */
	KC_F20                Keycode = 0x4000006f /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F20) */
	KC_F21                Keycode = 0x40000070 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F21) */
	KC_F22                Keycode = 0x40000071 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F22) */
	KC_F23                Keycode = 0x40000072 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F23) */
	KC_F24                Keycode = 0x40000073 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F24) */
	KC_Execute            Keycode = 0x40000074 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_EXECUTE) */
	KC_Help               Keycode = 0x40000075 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_HELP) */
	KC_Menu               Keycode = 0x40000076 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MENU) */
	KC_Select             Keycode = 0x40000077 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SELECT) */
	KC_Stop               Keycode = 0x40000078 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_STOP) */
	KC_Again              Keycode = 0x40000079 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AGAIN) */
	KC_Undo               Keycode = 0x4000007a /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_UNDO) */
	KC_Cut                Keycode = 0x4000007b /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CUT) */
	KC_Copy               Keycode = 0x4000007c /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_COPY) */
	KC_Paste              Keycode = 0x4000007d /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PASTE) */
	KC_Find               Keycode = 0x4000007e /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_FIND) */
	KC_Mute               Keycode = 0x4000007f /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MUTE) */
	KC_VolumeUp           Keycode = 0x40000080 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_VOLUMEUP) */
	KC_VolumeDown         Keycode = 0x40000081 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_VOLUMEDOWN) */
	KC_KP_Comma           Keycode = 0x40000085 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_COMMA) */
	KC_KP_EqualsAs400     Keycode = 0x40000086 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_EQUALSAS400) */
	KC_AltErase           Keycode = 0x40000099 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_ALTERASE) */
	KC_SysReq             Keycode = 0x4000009a /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SYSREQ) */
	KC_Cancel             Keycode = 0x4000009b /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CANCEL) */
	KC_Clear              Keycode = 0x4000009c /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CLEAR) */
	KC_Prior              Keycode = 0x4000009d /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PRIOR) */
	KC_Return2            Keycode = 0x4000009e /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RETURN2) */
	KC_Separator          Keycode = 0x4000009f /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SEPARATOR) */
	KC_Out                Keycode = 0x400000a0 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_OUT) */
	KC_Oper               Keycode = 0x400000a1 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_OPER) */
	KC_ClearAgain         Keycode = 0x400000a2 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CLEARAGAIN) */
	KC_CrSel              Keycode = 0x400000a3 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CRSEL) */
	KC_ExSel              Keycode = 0x400000a4 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_EXSEL) */
	KC_KP_00              Keycode = 0x400000b0 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_00) */
	KC_KP_000             Keycode = 0x400000b1 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_000) */
	KC_ThousandsSeparator Keycode = 0x400000b2 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_THOUSANDSSEPARATOR) */
	KC_DecimalSeparator   Keycode = 0x400000b3 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_DECIMALSEPARATOR) */
	KC_CurrencyUnit       Keycode = 0x400000b4 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CURRENCYUNIT) */
	KC_CurrencySubUnit    Keycode = 0x400000b5 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CURRENCYSUBUNIT) */
	KC_KP_LeftParen       Keycode = 0x400000b6 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_LEFTPAREN) */
	KC_KP_RightParen      Keycode = 0x400000b7 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_RIGHTPAREN) */
	KC_KP_LeftBrace       Keycode = 0x400000b8 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_LEFTBRACE) */
	KC_KP_RightBrace      Keycode = 0x400000b9 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_RIGHTBRACE) */
	KC_KP_Tab             Keycode = 0x400000ba /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_TAB) */
	KC_KP_Backspace       Keycode = 0x400000bb /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_BACKSPACE) */
	KC_KP_A               Keycode = 0x400000bc /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_A) */
	KC_KP_B               Keycode = 0x400000bd /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_B) */
	KC_KP_C               Keycode = 0x400000be /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_C) */
	KC_KP_D               Keycode = 0x400000bf /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_D) */
	KC_KP_E               Keycode = 0x400000c0 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_E) */
	KC_KP_F               Keycode = 0x400000c1 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_F) */
	KC_KP_Xor             Keycode = 0x400000c2 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_XOR) */
	KC_KP_Power           Keycode = 0x400000c3 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_POWER) */
	KC_KP_Percent         Keycode = 0x400000c4 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PERCENT) */
	KC_KP_Less            Keycode = 0x400000c5 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_LESS) */
	KC_KP_Greater         Keycode = 0x400000c6 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_GREATER) */
	KC_KP_Ampersand       Keycode = 0x400000c7 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_AMPERSAND) */
	KC_KP_DblAmpersand    Keycode = 0x400000c8 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DBLAMPERSAND) */
	KC_KP_VerticalBar     Keycode = 0x400000c9 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_VERTICALBAR) */
	KC_KP_DblVerticalBar  Keycode = 0x400000ca /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DBLVERTICALBAR) */
	KC_KP_Colon           Keycode = 0x400000cb /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_COLON) */
	KC_KP_Hash            Keycode = 0x400000cc /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_HASH) */
	KC_KP_Space           Keycode = 0x400000cd /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_SPACE) */
	KC_KP_At              Keycode = 0x400000ce /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_AT) */
	KC_KP_Exclam          Keycode = 0x400000cf /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_EXCLAM) */
	KC_KP_Memstore        Keycode = 0x400000d0 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMSTORE) */
	KC_KP_MemRecall       Keycode = 0x400000d1 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMRECALL) */
	KC_KP_MemClear        Keycode = 0x400000d2 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMCLEAR) */
	KC_KP_MemAdd          Keycode = 0x400000d3 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMADD) */
	KC_KP_MemSubtract     Keycode = 0x400000d4 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMSUBTRACT) */
	KC_KP_MemMultiply     Keycode = 0x400000d5 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMMULTIPLY) */
	KC_KP_MemDivide       Keycode = 0x400000d6 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMDIVIDE) */
	KC_KP_PlusMinus       Keycode = 0x400000d7 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PLUSMINUS) */
	KC_KP_Clear           Keycode = 0x400000d8 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_CLEAR) */
	KC_KP_ClearEntry      Keycode = 0x400000d9 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_CLEARENTRY) */
	KC_KP_Binary          Keycode = 0x400000da /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_BINARY) */
	KC_KP_Octal           Keycode = 0x400000db /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_OCTAL) */
	KC_KP_Decimal         Keycode = 0x400000dc /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DECIMAL) */
	KC_KP_Hexadecimal     Keycode = 0x400000dd /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_HEXADECIMAL) */
	KC_LCtrl              Keycode = 0x400000e0 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LCTRL) */
	KC_LShift             Keycode = 0x400000e1 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LSHIFT) */
	KC_LAlt               Keycode = 0x400000e2 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LALT) */
	KC_LGui               Keycode = 0x400000e3 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LGUI) */
	KC_RCtrl              Keycode = 0x400000e4 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RCTRL) */
	KC_RShift             Keycode = 0x400000e5 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RSHIFT) */
	KC_RAlt               Keycode = 0x400000e6 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RALT) */
	KC_RGui               Keycode = 0x400000e7 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RGUI) */
	KC_Mode               Keycode = 0x40000101 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MODE) */
	KC_Sleep              Keycode = 0x40000102 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SLEEP) */
	KC_Wake               Keycode = 0x40000103 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_WAKE) */
	KC_ChannelIncrement   Keycode = 0x40000104 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CHANNEL_INCREMENT) */
	KC_ChannelDecrement   Keycode = 0x40000105 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CHANNEL_DECREMENT) */
	KC_MediaPlay          Keycode = 0x40000106 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_PLAY) */
	KC_MediaPause         Keycode = 0x40000107 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_PAUSE) */
	KC_MediaRecord        Keycode = 0x40000108 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_RECORD) */
	KC_MediaFastForward   Keycode = 0x40000109 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_FAST_FORWARD) */
	KC_MediaRewind        Keycode = 0x4000010a /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_REWIND) */
	KC_MediaNextTrack     Keycode = 0x4000010b /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_NEXT_TRACK) */
	KC_MediaPreviousTrack Keycode = 0x4000010c /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_PREVIOUS_TRACK) */
	KC_MediaStop          Keycode = 0x4000010d /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_STOP) */
	KC_MediaEject         Keycode = 0x4000010e /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_EJECT) */
	KC_MediaPlayPause     Keycode = 0x4000010f /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_PLAY_PAUSE) */
	KC_MediaSelect        Keycode = 0x40000110 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_SELECT) */
	KC_AC_New             Keycode = 0x40000111 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_NEW) */
	KC_AC_Open            Keycode = 0x40000112 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_OPEN) */
	KC_AC_Close           Keycode = 0x40000113 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_CLOSE) */
	KC_AC_Exit            Keycode = 0x40000114 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_EXIT) */
	KC_AC_Save            Keycode = 0x40000115 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_SAVE) */
	KC_AC_Print           Keycode = 0x40000116 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_PRINT) */
	KC_AC_Properties      Keycode = 0x40000117 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_PROPERTIES) */
	KC_AC_Search          Keycode = 0x40000118 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_SEARCH) */
	KC_AC_Home            Keycode = 0x40000119 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_HOME) */
	KC_AC_Back            Keycode = 0x4000011a /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_BACK) */
	KC_AC_Forward         Keycode = 0x4000011b /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_FORWARD) */
	KC_AC_Stop            Keycode = 0x4000011c /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_STOP) */
	KC_AC_Refresh         Keycode = 0x4000011d /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_REFRESH) */
	KC_AC_Bookmarks       Keycode = 0x4000011e /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_BOOKMARKS) */
	KC_SoftLeft           Keycode = 0x4000011f /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SOFTLEFT) */
	KC_SoftRight          Keycode = 0x40000120 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SOFTRIGHT) */
	KC_Call               Keycode = 0x40000121 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CALL) */
	KC_EndCall            Keycode = 0x40000122 /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_ENDCALL) */
	KC_LeftTab            Keycode = 0x20000001 /**< Extended key Left Tab */
	KC_Level5Shift        Keycode = 0x20000002 /**< Extended key Level 5 Shift */
	KC_MultiKeyCompose    Keycode = 0x20000003 /**< Extended key Multi-key Compose */
	KC_LMeta              Keycode = 0x20000004 /**< Extended key Left Meta */
	KC_RMeta              Keycode = 0x20000005 /**< Extended key Right Meta */
	KC_LHyper             Keycode = 0x20000006 /**< Extended key Left Hyper */
	KC_RHyper             Keycode = 0x20000007 /**< Extended key Right Hyper */
)

/**
 * Valid key modifiers (possibly OR'd together).
 *
 * \since This datatype is available since SDL 3.2.0.
 */
type Keymod uint16

const (
	KM_None   Keymod = 0x0000                  /**< no modifier is applicable. */
	KM_LShift Keymod = 0x0001                  /**< the left Shift key is down. */
	KM_RShift Keymod = 0x0002                  /**< the right Shift key is down. */
	KM_Level5 Keymod = 0x0004                  /**< the Level 5 Shift key is down. */
	KM_LCtrl  Keymod = 0x0040                  /**< the left Ctrl (Control) key is down. */
	KM_RCtrl  Keymod = 0x0080                  /**< the right Ctrl (Control) key is down. */
	KM_LAlt   Keymod = 0x0100                  /**< the left Alt key is down. */
	KM_RAlt   Keymod = 0x0200                  /**< the right Alt key is down. */
	KM_LGui   Keymod = 0x0400                  /**< the left GUI key (often the Windows key) is down. */
	KM_RGui   Keymod = 0x0800                  /**< the right GUI key (often the Windows key) is down. */
	KM_Num    Keymod = 0x1000                  /**< the Num Lock key (may be located on an extended keypad) is down. */
	KM_Caps   Keymod = 0x2000                  /**< the Caps Lock key is down. */
	KM_Mode   Keymod = 0x4000                  /**< the !AltGr key is down. */
	KM_Scroll Keymod = 0x8000                  /**< the Scroll Lock key is down. */
	KM_Ctrl   Keymod = (KM_LCtrl | KM_RCtrl)   /**< Any Ctrl key is down. */
	KM_Shift  Keymod = (KM_LShift | KM_RShift) /**< Any Shift key is down. */
	KM_Alt    Keymod = (KM_LAlt | KM_RAlt)     /**< Any Alt key is down. */
	KM_Gui    Keymod = (KM_LGui | KM_RGui)     /**< Any GUI key is down. */
)
