package sdl

func init() {
    registerLoaderFunc(func() []externFunc {
        return []externFunc {
            { &CreateSurface, "SDL_CreateSurface" },
            { &CreateSurfaceFrom, "SDL_CreateSurfaceFrom" },
            { &DestroySurface, "SDL_DestroySurface" },
            { &GetSurfaceProperties, "SDL_GetSurfaceProperties" },
            { &SetSurfaceColorspace, "SDL_SetSurfaceColorspace" },
            { &GetSurfaceColorspace, "SDL_GetSurfaceColorspace" },
            { &CreateSurfacePalette, "SDL_CreateSurfacePalette" },
            { &SetSurfacePalette, "SDL_SetSurfacePalette" },
            { &GetSurfacePalette, "SDL_GetSurfacePalette" },
            { &AddSurfaceAlternateImage, "SDL_AddSurfaceAlternateImage" },
            { &SurfaceHasAlternateImages, "SDL_SurfaceHasAlternateImages" },
            { &RemoveSurfaceAlternateImages, "SDL_RemoveSurfaceAlternateImages" },
            { &LockSurface, "SDL_LockSurface" },
            { &UnlockSurface, "SDL_UnlockSurface" },
            { &LoadBMP_IO, "SDL_LoadBMP_IO" },
            { &LoadBMP, "SDL_LoadBMP" },
            { &SaveBMP_IO, "SDL_SaveBMP_IO" },
            { &SaveBMP, "SDL_SaveBMP" },
            { &SetSurfaceRLE, "SDL_SetSurfaceRLE" },
            { &SurfaceHasRLE, "SDL_SurfaceHasRLE" },
            { &SetSurfaceColorKey, "SDL_SetSurfaceColorKey" },
            { &SurfaceHasColorKey, "SDL_SurfaceHasColorKey" },
            { &GetSurfaceColorKey, "SDL_GetSurfaceColorKey" },
            { &SetSurfaceColorMod, "SDL_SetSurfaceColorMod" },
            { &GetSurfaceColorMod, "SDL_GetSurfaceColorMod" },
            { &SetSurfaceAlphaMod, "SDL_SetSurfaceAlphaMod" },
            { &GetSurfaceAlphaMod, "SDL_GetSurfaceAlphaMod" },
            { &SetSurfaceBlendMode, "SDL_SetSurfaceBlendMode" },
            { &GetSurfaceBlendMode, "SDL_GetSurfaceBlendMode" },
            { &SetSurfaceClipRect, "SDL_SetSurfaceClipRect" },
            { &GetSurfaceClipRect, "SDL_GetSurfaceClipRect" },
            { &FlipSurface, "SDL_FlipSurface" },
            { &DuplicateSurface, "SDL_DuplicateSurface" },
            { &ScaleSurface, "SDL_ScaleSurface" },
            { &ConvertSurface, "SDL_ConvertSurface" },
            { &ConvertSurfaceAndColorspace, "SDL_ConvertSurfaceAndColorspace" },
            { &ConvertPixels, "SDL_ConvertPixels" },
            { &ConvertPixelsAndColorspace, "SDL_ConvertPixelsAndColorspace" },
            { &PremultiplyAlpha, "SDL_PremultiplyAlpha" },
            { &PremultiplySurfaceAlpha, "SDL_PremultiplySurfaceAlpha" },
            { &ClearSurface, "SDL_ClearSurface" },
            { &FillSurfaceRect, "SDL_FillSurfaceRect" },
            { &FillSurfaceRects, "SDL_FillSurfaceRects" },
            { &BlitSurface, "SDL_BlitSurface" },
            { &BlitSurfaceUnchecked, "SDL_BlitSurfaceUnchecked" },
            { &BlitSurfaceScaled, "SDL_BlitSurfaceScaled" },
            { &BlitSurfaceUncheckedScaled, "SDL_BlitSurfaceUncheckedScaled" },
            { &StretchSurface, "SDL_StretchSurface" },
            { &BlitSurfaceTiled, "SDL_BlitSurfaceTiled" },
            { &BlitSurfaceTiledWithScale, "SDL_BlitSurfaceTiledWithScale" },
            { &BlitSurface9Grid, "SDL_BlitSurface9Grid" },
            { &MapSurfaceRGB, "SDL_MapSurfaceRGB" },
            { &MapSurfaceRGBA, "SDL_MapSurfaceRGBA" },
            { &ReadSurfacePixel, "SDL_ReadSurfacePixel" },
            { &ReadSurfacePixelFloat, "SDL_ReadSurfacePixelFloat" },
            { &WriteSurfacePixel, "SDL_WriteSurfacePixel" },
            { &WriteSurfacePixelFloat, "SDL_WriteSurfacePixelFloat" },
        }
    })
}
